### ISSUE TITLE
`Chain` is broken with contextual rules

### ISSUE THREAD

**Issue by ctrlcctrlv** [simoncozens/fontFeatures#8]
```fea
Feature ccmp {
    Routine MEDI {
        Substitute @lower -> @lower.low;
    };

    Chain @lower { @lower (MEDI) };
};
```

Beyond confused I'm afraid.

```
Parse error at line 29, column 5: expected EOF. trail: [Feature_Args statement]
```

**Comment by simoncozens** [comment]
That *is* meant to work. parsley's error handling is awful but the fact that it hasn't descended into the Chain statement suggests that it hasn't recognised the verb. Can you just try a simple thing `Chain @lower (MEDI);` to see if it works at all? Then maybe we can see what's wrong with the contextual.

**Comment by ctrlcctrlv** [comment]
That works, but only if I force -O0, otherwise I get:

```
Press ENTER or type command to continue
Traceback (most recent call last):
  File "/home/fred/.local/bin/fee2fea", line 4, in <module>
    __import__('pkg_resources').run_script('fontFeatures==1.0.3', 'fee2fea')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/fred/.local/lib/python3.9/site-packages/fontFeatures-1.0.3-py3.9.egg/EGG-INFO/scripts/fee2fea", line 41, in <module>
    Optimizer(p.fontfeatures).optimize(level=args.O)
  File "/home/fred/.local/lib/python3.9/site-packages/fontFeatures-1.0.3-py3.9.egg/fontFeatures/optimizer/__init__.py", line 20, in optimize
    self.optimize_routine(r, level)
  File "/home/fred/.local/lib/python3.9/site-packages/fontFeatures-1.0.3-py3.9.egg/fontFeatures/optimizer/__init__.py", line 33, in optimize_routine
    optimization().apply(r, self.ff)
  File "/home/fred/.local/lib/python3.9/site-packages/fontFeatures-1.0.3-py3.9.egg/fontFeatures/optimizer/Routine.py", line 46, in apply
    if len(routine.rules) < 2:
AttributeError: 'RoutineReference' object has no attribute 'rules'
```

Even with -O0, the longer version results in:

```
Press ENTER or type command to continue
Traceback (most recent call last):
  File "/home/fred/.local/bin/fee2fea", line 4, in <module>
    __import__('pkg_resources').run_script('fontFeatures==1.0.3', 'fee2fea')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/fred/.local/lib/python3.9/site-packages/fontFeatures-1.0.3-py3.9.egg/EGG-INFO/scripts/fee2fea", line 40, in <module>
    p.parseFile(args.fee)
  File "/home/fred/.local/lib/python3.9/site-packages/fontFeatures-1.0.3-py3.9.egg/fontFeatures/feeLib/__init__.py", line 202, in parseFile
    return self.parseString(data)
  File "/home/fred/.local/lib/python3.9/site-packages/fontFeatures-1.0.3-py3.9.egg/fontFeatures/feeLib/__init__.py", line 210, in parseString
    fee = self.parser(s).feefile()
  File "/home/fred/.local/lib/python3.9/site-packages/Parsley-1.3-py3.9.egg/parsley.py", line 98, in invokeRule
    raise err
ometa.runtime.ParseError: 
    Chain @Latn_lower { @Latn_lower (MEDI) };
     ^
Parse error at line 29, column 5: expected EOF. trail: [Feature_Args statement]
```

**Comment by simoncozens** [comment]
Ah, yeah, the optimiser is currently broken after I rejigged the way routines appear in features. And yes, it looks like there is a problem with the parser distinguishing between contextual and non-contextual chaining rules. Which is odd because I stole that bit of the grammar from Substitute, which *definitely* works. I'll take a look.

**Comment by ctrlcctrlv** [comment]
I've tried to fix this and all I can say is that Parsley is very hard to understand...do you know how to view the files it refers to as e.g. `pymeta_generated_code/pymeta_grammar__Grammar.py`, `pymeta_generated_code/pymeta_grammar__Grammar8.py`? I think reading the generated code would help me but don't know what to Google and the pymeta docs aren't helping, so I thought you might know.
